(()=>{
 const f=document.querySelector('#sffqForm'),status=document.querySelector('#saveStatus'),followup=location.pathname.endsWith('/followup.html'),storageKey=followup?'sffq:followup':'sffq:first-half';
 const rows=document.querySelector('#otherFoodRows');
 const addRow=(name='',amount='')=>{if(!rows)return;const row=document.createElement('div');row.className='other-food-row';row.innerHTML='<input type="text" class="other-name" placeholder="食物名称" aria-label="食物名称"><input type="number" class="other-amount" min="0.1" step="0.1" inputmode="decimal" placeholder="重量（两）" aria-label="重量（两）"><button type="button" aria-label="删除食物">删除</button>';row.querySelector('.other-name').value=name;row.querySelector('.other-amount').value=amount;row.querySelector('button').onclick=()=>{row.remove();store()};rows.append(row)};
 let saved={};try{saved=JSON.parse(localStorage.getItem(storageKey)||'{}');for(const [name,val] of Object.entries(saved)){if(name==='other_food_rows')continue;const inputs=f.querySelectorAll(`[name="${CSS.escape(name)}"]`);if(inputs[0]?.type==='radio')inputs.forEach(r=>r.checked=r.value===val);else if(inputs[0])inputs[0].value=val}saved.other_food_rows?.forEach(r=>addRow(r.name,r.amount))}catch{}
 const update=()=>{f.querySelectorAll('.extra[data-for]').forEach(label=>{const selected=f.elements.namedItem(label.dataset.for)?.value||'';const show=selected.includes('以上')||selected.includes('大于')||selected.includes('其他用量');label.classList.toggle('visible',show);label.querySelector('input').disabled=!show});const dha=document.querySelector('#dhaProducts');if(dha)dha.hidden=f.elements.namedItem('dha_used')?.value!=='有';const other=document.querySelector('#otherFoods');if(other)other.hidden=f.elements.namedItem('other_food_used')?.value!=='有'};
 const data=()=>{const d=Object.fromEntries(new FormData(f));if(followup)d.other_food_rows=[...rows.querySelectorAll('.other-food-row')].map(r=>({name:r.querySelector('.other-name').value.trim(),amount:r.querySelector('.other-amount').value})).filter(r=>r.name||r.amount);return d};
 const store=()=>{try{localStorage.setItem(storageKey,JSON.stringify(data()))}catch{status.textContent='自动暂存失败，请检查浏览器存储空间'}};
 f.addEventListener('change',()=>{update();store()});f.addEventListener('input',store);document.querySelector('#addFood')?.addEventListener('click',()=>{addRow();store()});update();
 f.addEventListener('submit',e=>{e.preventDefault();for(const label of f.querySelectorAll('.extra.visible')){const input=label.querySelector('input');if(!input.value||!input.checkValidity()){input.focus();status.textContent='请填写所选的具体数量';return}}if(followup&&f.elements.namedItem('other_food_used')?.value==='有'&&(!data().other_food_rows.length||data().other_food_rows.some(r=>!r.name||!r.amount))){status.textContent='请填写食物名称与重量';rows.querySelector('input')?.focus();return}
 store();if(!followup){location.href='followup.html';return}
 let first={};try{first=JSON.parse(localStorage.getItem('sffq:first-half')||'{}')}catch{}const payload={type:'sffq',data:{...first,...data()}};if(window.webkit?.messageHandlers?.saveForm)window.webkit.messageHandlers.saveForm.postMessage(payload);else if(window.Android?.saveForm)window.Android.saveForm(JSON.stringify(payload));else{console.log('[SFFQ]',payload);status.textContent='问卷已保存在此浏览器'}
 });
})();
