(function(){
 var root=document.querySelector('[data-kind]'),kind=root.dataset.kind,page=root.dataset.page,key='benbing_'+kind+'_records';
 var defaults={zhongchengyao:[{name:'痹祺胶囊',frequency:'日1次',dose:'4',summary:'日1次，单次4片/粒'}],'zhongyao-tangji':[{name:'汤剂1',startDate:'2022-01-22',summary:'2022年1月22日'}],'fei-yaowu-liaofa':[{name:'八段锦',frequency:'一周1次',duration:'60',summary:'一周1次，单次60分钟'}]};
 function read(){try{var raw=localStorage.getItem(key);var value=raw===null?defaults[kind]:JSON.parse(raw);return Array.isArray(value)?value:[];}catch(e){return defaults[kind];}}
 var items=read();
 function display(item){if(item.summary)return item.summary;if(kind==='zhongyao-tangji')return item.startDate||'';if(kind==='fei-yaowu-liaofa')return [item.frequency,item.duration?'单次'+item.duration+'分钟':''].filter(Boolean).join('，');return [item.frequency,item.dose?'单次'+item.dose+'片/粒':''].filter(Boolean).join('，');}
 if(page==='list'){var list=document.getElementById('items');document.getElementById('empty').hidden=items.length>0;items.forEach(function(item,i){var li=document.createElement('li'),a=document.createElement('a'),copy=document.createElement('span'),name=document.createElement('strong'),note=document.createElement('small'),arrow=document.createElement('span');li.className='med-item';a.href='add-'+kind+'.html?edit='+i;name.textContent=item.name;note.textContent=display(item);arrow.className='chevron';arrow.textContent='›';arrow.setAttribute('aria-hidden','true');copy.append(name,note);a.append(copy,arrow);li.appendChild(a);list.appendChild(li);});return;}
 var form=document.getElementById('entryForm'),details=document.getElementById('details'),stopped=document.getElementById('stopped'),custom=form.elements.customName,message=document.getElementById('message'),edit=Number(new URLSearchParams(location.search).get('edit'));if(!new URLSearchParams(location.search).has('edit'))edit=-1;
 if(edit>=0&&edit<items.length){var item=items[edit];form.elements.hasEntry.value='有';['name','frequency','dose','duration','startDate','endDate','ongoing','reason'].forEach(function(prop){if(form.elements[prop])form.elements[prop].value=item[prop]||'';});if(form.elements.name&&form.elements.name.value!==item.name){form.elements.name.value='其他';if(custom)custom.value=item.name;}}
 function refresh(){details.hidden=form.elements.hasEntry.value==='无';if(custom)custom.hidden=form.elements.name.value!=='其他';if(stopped)stopped.hidden=form.elements.ongoing.value!=='否';}
 form.addEventListener('change',refresh);refresh();
 form.addEventListener('submit',function(e){e.preventDefault();message.textContent='';if(form.elements.hasEntry.value==='无'){localStorage.setItem(key,JSON.stringify([]));location.href=kind+'.html';return;}
  var data={name:kind==='zhongyao-tangji'?'汤剂'+(edit>=0?edit+1:items.length+1):form.elements.name.value,frequency:form.elements.frequency?form.elements.frequency.value:'',dose:form.elements.dose?form.elements.dose.value:'',duration:form.elements.duration?form.elements.duration.value:'',startDate:form.elements.startDate?form.elements.startDate.value:'',endDate:form.elements.endDate?form.elements.endDate.value:'',ongoing:form.elements.ongoing?form.elements.ongoing.value:'',reason:form.elements.reason?form.elements.reason.value:''};
  if(data.name==='其他')data.name=custom.value.trim();if(!data.name){message.textContent='请选择或填写名称';return;}if(kind!=='zhongyao-tangji'&&(!data.frequency||(kind==='zhongchengyao'&&!data.dose)||(kind==='fei-yaowu-liaofa'&&!data.duration))){message.textContent='请填写频次及用量或时长';return;}
  if(stopped&&data.ongoing!=='否'){data.endDate='';data.reason='';}if(data.startDate&&data.endDate&&data.endDate<data.startDate){message.textContent='结束日期不能早于开始日期';return;}
  if(edit>=0&&edit<items.length)items[edit]=data;else items.push(data);try{localStorage.setItem(key,JSON.stringify(items));location.href=kind+'.html';}catch(error){message.textContent='保存失败，请检查浏览器存储设置';}
 });
})();
